export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SAVE_USER_DETAILS = 'SAVE_USER_DETAILS';
export const SAVE_USER_DETAILS_SUCCESS = 'SAVE_USER_DETAILS_SUCCESS';
// export const SAVE_USER_DETAILS_FAILED = 'SAVE_USER_DETAILS_FAILED';


export const SAVE_COMICS = 'SAVE_COMICS';
export const SAVE_COMICS_SUCCESS = 'SAVE_COMICS_SUCCESS';
export const SAVE_COMICS_FAILED = 'SAVE_COMICS_FAILED';
export const FETCH_COMICS_START = 'FETCH_COMICS_START'
export const FETCH_COMICS_SUCCESS = 'FETCH_COMICS_SUCCESS'
export const FETCH_COMICS_FAILED = 'FETCH_COMICS_FAILED'

export const SAVE_CHARACTERS = 'SAVE_CHARACTERS';
export const SAVE_CHARACTERS_SUCCESS = 'SAVE_CHARACTERS_SUCCESS';
export const SAVE_CHARACTERS_FAILED = 'SAVE_CHARACTERS_FAILED';
export const FETCH_CHARACTERS_START = 'FETCH_CHARACTERS_START'
export const FETCH_CHARACTERS_SUCCESS = 'FETCH_CHARACTERS_SUCCESS'
export const FETCH_CHARACTERS_FAILED = 'FETCH_CHARACTERS_FAILED'